include ../Makefile

CLEANFILES =

OBJS =\
	../apc_cache.o\
	../apc_cache_mm.o\
	../apc_crc32.o\
	../apc_fcntl.o\
	../apc_iface.o\
	../apc_lib.o\
	../apc_nametable.o\
	../apc_rwlock.o\
	../apc_sem.o\
	../apc_serialize.o\
	../apc_shm.o\
	../apc_smm.o\
	../apc_util.o\
	../php_apc.o

all:

#
#
#

#PROGRAM_NAME         = example
#PROGRAM_SOURCES      = example.c
#PROGRAM_LDADD        = $(PHP_SRC_DIR)/libphp4.la
#PROGRAM_LDFLAGS      = -export-dynamic
#PROGRAM_DEPENDENCIES = $(PROGRAM_LDADD)
#
#example: $(PROGRAM_DEPENDENCIES) example.lo $(OBJS)
#	$(LINK) $(PROGRAM_LDFLAGS) example.lo $(OBJS) $(PROGRAM_LDADD)

